# Crib Analyser
# Program to do stats on the hand scores generated by cribCounter
# Joe Jeffers
# 23 Apr 2015
# License GPL v2.0

# Open the requisite files
scoreFile = open('cribScores.csv')
statFile = open('cribStats.txt','w')
scores = []

# Git rid of the headers
headers = scoreFile.readline()

# for each line, get the stats
for line in scoreFile.readlines():
	x = line.split(',')
	tot = int(x[0])
	if(tot == 19):
		print(x)
	scores.append(tot)
scoreFile.close()

# Infrastructure for the statistics
breakdown = dict()
tot = 0
low = 0
high = 0
nt = 0

# Do Math!
for score in scores:
	tot += score
	if(score > high):
		high = score
	if(score == 19):
		nt += 1
	if(score not in breakdown):
		breakdown[score] = 1
	else:
		breakdown[score] += 1

# Print out the results.
statFile = open('cribStats.txt','w')
print('Average Hand Score: ' + str(tot/len(scores)))
print('Max of Possible Score: ' + str(high))
print('Any nineteens? ' + str(nt))
print('Score Breakdown: ')
statFile.write('Average Hand Score: ' + str(tot/len(scores)) + '\n')
statFile.write('Max of Possible Score: ' + str(high) + '\n')
statFile.write('Any nineteens? ' + str(nt) + '\n')
statFile.write('Score Breakdown: ' + '\n')
i = 0
while(i <= 29):
	print(str(i) + '	' + breakdown[str(i)])
	statFile.write(str(i) + '	' + breakdown[str(i)] + '\n')
statFile.close()
